#### Data information ####

result_folder_path: "results/processed_kettling"
sim_analysis_evolution_data_name: "evolution_data.csv"

time_column_name: "cycle"

main_config_params:
- "P_ratio_officer_protester"
- "P_emotional_contagion_activated"
- "P_use_damageable_items"

# should be common to all species
xloc_var_name: "x"
yloc_var_name: "y"

#### App information ####

ticks_per_range: 10
n_potential_values_continuous_slider: 20

# information here: https://plotly.com/python/marker-style/
species_to_symbol:
  rioter: "triangle-down"
  police_officer: "star"
  item: "diamond"




