model.device: cuda
model.update_node_module.name: MyGATConv
model.update_node_module.parameters.add_self_loops: false
model.update_node_module.parameters.bias: false
model.update_node_module.parameters.concat: true
model.update_node_module.parameters.dropout: 0.0
model.update_node_module.parameters.dst_content_mask.0: false
model.update_node_module.parameters.dst_content_require_grad: true
model.update_node_module.parameters.dst_content_weight_initializer: glorot
model.update_node_module.parameters.dst_edge_mask.0: false
model.update_node_module.parameters.dst_edge_require_grad: true
model.update_node_module.parameters.dst_edge_weight_initializer: glorot
model.update_node_module.parameters.edge_dim: 1
model.update_node_module.parameters.edge_weight_initializer: glorot
model.update_node_module.parameters.fill_value: mean
model.update_node_module.parameters.heads: 1
model.update_node_module.parameters.in_channels.0: 1
model.update_node_module.parameters.in_channels.1: 1
model.update_node_module.parameters.negative_slope: 1.0
model.update_node_module.parameters.out_channels: 1
model.update_node_module.parameters.src_content_mask.0: true
model.update_node_module.parameters.src_content_require_grad: false
model.update_node_module.parameters.src_content_weight_initializer: ones
model.update_node_module.parameters.src_edge_mask.0: true
model.update_node_module.parameters.src_edge_require_grad: true
model.update_node_module.parameters.src_edge_weight_initializer: glorot
other.model_fit_params.early_stopping_monitor: train_mae
other.model_fit_params.epochs: 10000
other.model_fit_params.l2_reg: 0.01
other.model_fit_params.patience: 500
other.model_fit_params.report_epoch_steps: 1
other.model_name: GAT_liking_sim_amp_3NN_3ExpNN_no_val_bias-False_att-liking-True_amp-liking-False
other.sim_used: original
preprocessing_pipeline.complete_train_mask_selector.name: MaskLowerThanSelector
preprocessing_pipeline.complete_train_mask_selector.parameters.feature_name: experience
preprocessing_pipeline.complete_train_mask_selector.parameters.threshold: 0
preprocessing_pipeline.complete_train_mask_selector.parameters.verbose: true
preprocessing_pipeline.validation_handler.name: MaskLowerThanSelector
preprocessing_pipeline.validation_handler.parameters.feature_name: experience
preprocessing_pipeline.validation_handler.parameters.threshold: 0
preprocessing_pipeline.validation_handler.parameters.verbose: true
varying_params: []
