model:
  name: RandomNormalModel
  parameters:
    dim_out: 1
    mean: 0
    std: 1
other:
  model_fit_params: {}
  model_name: baseline_randn01
  sim_used: original
preprocessing_pipeline:
  complete_train_mask_selector:
    name: MaskLowerThanSelector
    parameters:
      feature_name: experience
      threshold: 0
      verbose: true
  transformators:
  - name: KeepGroupSendersToGroupReceivers
    parameters:
      group_receivers_mask_fn: <lambda>
      group_receivers_mask_threshold_fn: null
      group_receivers_thresholding: false
      group_senders_mask_fn: <lambda>
      group_senders_mask_threshold_fn: null
      group_senders_thresholding: false
      verbose: true
  - name: KeepFeatureNamedSelector
    parameters:
      feature_names_kept:
      - liking
      verbose: true
  validation_handler:
    name: MaskLowerThanSelector
    parameters:
      feature_name: experience
      threshold: 0
      verbose: true
