model.name: SimpleConvModel
model.parameters.aggr: mean
other.model_name: baseline_mean
other.sim_used: original
preprocessing_pipeline.complete_train_mask_selector.name: MaskLowerThanSelector
preprocessing_pipeline.complete_train_mask_selector.parameters.feature_name: experience
preprocessing_pipeline.complete_train_mask_selector.parameters.threshold: 0
preprocessing_pipeline.complete_train_mask_selector.parameters.verbose: true
preprocessing_pipeline.transformators.0.name: KeepGroupSendersToGroupReceivers
preprocessing_pipeline.transformators.0.parameters.group_receivers_mask_fn: <lambda>
preprocessing_pipeline.transformators.0.parameters.group_receivers_thresholding: false
preprocessing_pipeline.transformators.0.parameters.group_senders_mask_fn: <lambda>
preprocessing_pipeline.transformators.0.parameters.group_senders_thresholding: false
preprocessing_pipeline.transformators.0.parameters.verbose: true
preprocessing_pipeline.transformators.1.name: KeepFeatureNamedSelector
preprocessing_pipeline.transformators.1.parameters.feature_names_kept.0: liking
preprocessing_pipeline.transformators.1.parameters.verbose: true
preprocessing_pipeline.validation_handler.name: MaskLowerThanSelector
preprocessing_pipeline.validation_handler.parameters.feature_name: experience
preprocessing_pipeline.validation_handler.parameters.threshold: 0
preprocessing_pipeline.validation_handler.parameters.verbose: true
varying_params:
- preprocessing_pipeline.transformators.0.parameters.group_senders_mask_threshold_fn
- preprocessing_pipeline.transformators.0.parameters.group_receivers_mask_threshold_fn
