model:
  name: SimpleConvModel
  parameters:
    aggr: mean
other:
  model_fit_params: {}
  model_name: 6NN_mean
  sim_used: original
preprocessing_pipeline:
  complete_train_mask_selector:
    name: MaskLowerThanSelector
    parameters:
      feature_name: experience
      threshold: 0
      verbose: true
  transformators:
  - name: KeepGroupSendersToGroupReceivers
    parameters:
      group_receivers_mask_fn: <lambda>
      group_receivers_mask_threshold_fn: null
      group_receivers_thresholding: false
      group_senders_mask_fn: <lambda>
      group_senders_mask_threshold_fn: null
      group_senders_thresholding: false
      verbose: true
  - name: KeepKNearestNeighbors
    parameters:
      edge_attr_names_used:
      - _sim
      k: 6
      ord: 1
      verbose: true
  - name: KeepFeatureNamedSelector
    parameters:
      feature_names_kept:
      - liking
      verbose: true
  validation_handler:
    name: MaskLowerThanSelector
    parameters:
      feature_name: experience
      threshold: 0
      verbose: true
